<?php

namespace Louvre\GeneralBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * BookingRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BookingRepository extends EntityRepository
{
    public function getNumberTicketByDay()
    {
        $qb = $this
            ->createQueryBuilder('b')
            ->leftJoin('b.tickets', 'tick')
            ->addSelect('tick');

        return $qb
            ->getQuery()
            ->getResult();
    }

    public function getBookingWithTicket(array $ticketNumber)
    {
        $qb = $this->createQueryBuilder('b');

        // on fait une jointure avec l'entité Ticket avec pour alias "t"
        $qb
            ->innerJoin('b.tickets', 't')
            ->addSelect('t');

        // on filtre sur le nombre de tickets à l'aide d'un count
        $qb->where($qb->expr()->count('t.id', $ticketNumber));

        // enfin, on retourne le résultat
        return $qb
            ->getQuery()
            ->getResult();
    }
}
