root_homepage:
    path:     /
    defaults: { _controller: GeneralBundle:Navigation:home }

general_homepage:
    path:     /louvre/accueil
    defaults: { _controller: GeneralBundle:Navigation:home }
    
#tickets:
#    path:     /louvre/tickets
#    defaults: { _controller: GeneralBundle:Ticket:ticketForm }
    
selection:
    path:     /louvre/billetterie/selection
    defaults: { _controller: GeneralBundle:Booking:bookingForm }
    
recapitulatif:
    path:     /louvre/billetterie/recapitulatif/{id}
    defaults: { _controller: GeneralBundle:BookingSummary:bookingSummary }
    
modification:
    path:     /louvre/billetterie/recapitulatif/modification/{id}
    defaults: { _controller: GeneralBundle:BookingSummary:edit }

confirmation:
    path:     /louvre/billetterie/confirmation
    defaults: { _controller: GeneralBundle:Confirmation:confirmation}


register:
    path:     /louvre/billetterie/inscription
    defaults: { _controller: GeneralBundle:User:register }

connexion:
    path:     /louvre/connexion
    defaults: { _controller: GeneralBundle:Security:login }

deconnexion:
    path:     /louvre/deconnexion
    defaults: { _controller: GeneralBundle:Security:logout}




louvre_test_translation:
    path:     /traduction/{name}
    defaults: { _controller: GeneralBundle:Translation:translate }




order_prepare:
    path:     /louvre/billetterie/commande/prepare/{id}
    defaults: { _controller: GeneralBundle:Stripe:prepare }
    
order_checkout:
    path:     /louvre/billetterie/commande/checkout
    defaults: { _controller: GeneralBundle:Stripe:checkout }
    