general_homepage:
    path:     /louvre
    defaults: { _controller: GeneralBundle:Navigation:accueil }
    
tickets:
    path:     /louvre/tickets
    defaults: { _controller: GeneralBundle:Ticket:ticketFormulaire }
    
selection:
    path:     /louvre/billetterie/selection
    defaults: { _controller: GeneralBundle:Commande:commandeFormulaire }
    
récapitulatif:
    path:     /louvre/billetterie/recapitulatif
    defaults: { _controller: GeneralBundle:Recap:commandeRecap }
    
modification:
    path:     /louvre/billetterie/recapitulatif/modification/{id}
    defaults: { _controller: GeneralBundle:Recap:edit }

connexion:
    path:     /louvre/billetterie/connexion
    defaults: { _controller: GeneralBundle:Security:login }

deconnexion:
    path:     /louvre/billetterie/deconnexion
    defaults: { _controller: GeneralBundle:Security:logout}




list:
    path:     /louvre/list
    defaults: { _controller: GeneralBundle:Commande:commandes_list }
    
edit:
    path:     /louvre/edit/{id}
    defaults: { _controller: GeneralBundle:Commande:edit }
    
delete:
    path:     /louvre/delete/{id}
    defaults: { _controller: GeneralBundle:Commande:delete }






order_prepare:
    path:     /louvre/billetterie/order/prepare
    defaults: { _controller: GeneralBundle:Order:prepare }
    
order_checkout:
    path:     /louvre/billetterie/order/checkout
    defaults: { _controller: GeneralBundle:Order:checkout }
    