general_homepage:
    path:     /louvre/accueil
    defaults: { _controller: GeneralBundle:Navigation:home }
    
#tickets:
#    path:     /louvre/tickets
#    defaults: { _controller: GeneralBundle:Ticket:ticketForm }
    
selection:
    path:     /louvre/billetterie/selection
    defaults: { _controller: GeneralBundle:Booking:bookingForm }
    
récapitulatif:
    path:     /louvre/billetterie/recapitulatif
    defaults: { _controller: GeneralBundle:BookingSummary:bookingSummary }
    
modification:
    path:     /louvre/billetterie/recapitulatif/modification/{id}
    defaults: { _controller: GeneralBundle:BookingSummary:edit }

register:
    path:     /louvre/billetterie/inscription
    defaults: { _controller: GeneralBundle:User:register }

connexion:
    path:     /louvre/billetterie/connexion
    defaults: { _controller: GeneralBundle:Security:login }

deconnexion:
    path:     /louvre/billetterie/deconnexion
    defaults: { _controller: GeneralBundle:Security:logout}

confirmation:
    path:     /louvre/billetterie/confirmation
    defaults: { _controller: GeneralBundle:Confirmation:confirmation}



louvre_test_translation:
    path:     /traduction/{name}
    defaults: { _controller: GeneralBundle:Translation:translate }




list:
    path:     /louvre/list
    defaults: { _controller: GeneralBundle:Booking:commandes_list }
    
edit:
    path:     /louvre/edit/{id}
    defaults: { _controller: GeneralBundle:Booking:edit }
    
delete:
    path:     /louvre/delete/{id}
    defaults: { _controller: GeneralBundle:Booking:delete }






order_prepare:
    path:     /louvre/billetterie/commande/prepare
    defaults: { _controller: GeneralBundle:Stripe:prepare }
    
order_checkout:
    path:     /louvre/billetterie/commande/checkout
    defaults: { _controller: GeneralBundle:Stripe:checkout }
    